[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
jito_security_module = "FqrKisaNRa1b2xF2FeJNDsNKPNQHsPcvAkcCn28SHnmg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lucasbruder/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
