[package]
name = "jito-restaking-cli"
description = "Jito's Restaking CLI"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }

[dependencies]

[dev-dependencies]

